Project1
ViktorPetrovichBarinov/Tinkoff-23-24 pull request #2
Opened 2023-10-22 11:21 UTC by ViktorPetrovichBarinov

2023-10-24 21:23 UTC, infomouse requested changes

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +
Старайтесь писать код более аккуратно и избегать отступов в несколько пустых строк.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +    private final int maxLength = 15;
Значения очень похоже на константы. Может сделать их такими?

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +    private final ArrayList<String> dictionary;
При объявлении переменных надо стараться использовать интерфейсы, а не конкретные реализации в качестве типа. В данном случае должен быть List<String>, тогда в будущем можно заменить ArrayList на LinkedList.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +        dictionary = new ArrayList<>();
Если вы хотите получить гибкий, легко расширяемый и тестируемый код, то таких инициализаций в конструкторе нужно избегать. Нужно в конструктор передавать уже готовый List.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +            int randIndex = this.rand.nextInt(this.dictionary.size());
Обычно this опускают, если нет конфликта имен.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Main.java
> +                System.out.println("\u001B[35mEnter only one letter\u001B[0m");
Этот блок можно вынести в метод, чтобы улучшить читаемость кода.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Session.java
> +    public boolean mistakesUp() {
Не совсем корректно с точки зрения проектирования. Класс сам должен увеличивать попытки в методе tryLetter, это его ответственность. Извне можно только текущее состояние запрашивать, но не изменять.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Session.java
> +    public boolean mistakesUp() {
Есть такая практика: методы, которые возвращают boolean называть с префиксом is. Например, isNumber, isEmpty, isGameOver и тд. Предлагаю ее придерживаться.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Session.java
> +    public boolean correctInput(String str) {
На будущее: надо учиться разделять код на классы, учитывая зоны ответственности. Например, валидацией входной строки класс Session не должен заниматься.

2023-10-24 21:23 UTC, infomouse commented on src/main/java/edu/project1/Main.java
>      public static void main(String[] args) {
Старайтесь избегать писать логику в мейн методе. Все его содержимое должно быть в методе отдельного класса, например, HangmanGame.run().
В мейне же должен быть только запуск такого класса:
```java
    public static void main(String[] args) {
        Dictionary dictionary = new Dictionary();
        int maxMistakes = 5;
        HangmanGame hangmanGame = new HangmanGame(dictionary, maxMistakes);
        hangmanGame.run();
    }
```

2023-10-26 07:00 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Dictionary.java
> +
+

2023-10-26 07:02 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Dictionary.java
> +    private final int maxLength = 15;
+

2023-10-26 07:03 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Dictionary.java
> +    private final ArrayList<String> dictionary;
+

2023-10-26 07:12 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Dictionary.java
> +        dictionary = new ArrayList<>();
+

2023-10-26 07:13 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Dictionary.java
> +            int randIndex = this.rand.nextInt(this.dictionary.size());
+

2023-10-26 08:01 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Main.java
> +                System.out.println("\u001B[35mEnter only one letter\u001B[0m");
+

2023-10-26 08:17 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Session.java
> +    public boolean mistakesUp() {
+

2023-10-26 08:19 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/project1/Session.java
> +    public boolean mistakesUp() {
+

2023-10-29 21:27 UTC, infomouse approved these changes

2023-10-29 21:27 UTC, infomouse commented on src/main/java/edu/project1/Dictionary.java
> +    public Dictionary(ArrayList<String> dictionary) {
Тоже должен быть List.

2023-10-29 21:27 UTC, infomouse commented on src/main/java/edu/project1/Session.java
> +    public void firstWords() {
Размазали логику взаимодействия с консолью по нескольким классам. Такого быть не должно. В следующий раз попробуйте сделать абстракцию над вводом-выводом и использовать ее только в одном классе.

2023-11-24 18:29 UTC, merged