Hw2
ViktorPetrovichBarinov/Tinkoff-23-24 pull request #3
Opened 2023-10-22 18:17 UTC by ViktorPetrovichBarinov

2023-10-24 07:14 UTC, infomouse requested changes

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task1/Addition.java
> +package edu.hw2.Task1;
В джаве имена пакетов должны быть в ловеркейсе.
https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task4/Task4.java
> +public class Task4 {
Нет юнит-тестов.

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task4/Task4.java
> +    @SuppressWarnings("RegexpSinglelineJava")
Зачем это?

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task4/Task4.java
> +            System.out.println(stackTrace[i]);
Дебаг кода не должно быть.

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task3/ConnectionException.java
> +    public ConnectionException(Throwable th) {
Не надо экономить буквы. Это ухудшает читаемость кода. В данном случае либо throwable, либо cause.

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task3/ConnectionException.java
> +        super("Connection Exception");
Суть message не в дублировании имени исключения, а в более детальном описании проблемы. А это можно сделать только в месте возникновения ошибки.

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +public final class PopularCommandExecutor {
Нет юнит-тестов.

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task3/FaultyConnection.java
> +public class FaultyConnection implements Connection {
Не выполнено требование:
проблемное соединение иногда бросает ConnectionException

2023-10-24 07:14 UTC, infomouse commented on src/main/java/edu/hw2/Task3/DefaultConnectionManager.java
> +public class DefaultConnectionManager implements ConnectionManager {
Не выполнено требование:
DefaultConnectionManager, который с некоторой вероятностью возвращает проблемное соединение

2023-10-26 05:51 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task1/Addition.java
> +package edu.hw2.Task1;
+

2023-10-26 06:07 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task4/Task4.java
> +public class Task4 {
+

2023-10-26 06:10 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task4/Task4.java
> +    @SuppressWarnings("RegexpSinglelineJava")
+

2023-10-26 06:10 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task4/Task4.java
> +            System.out.println(stackTrace[i]);
+

2023-10-26 06:12 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task3/ConnectionException.java
> +    public ConnectionException(Throwable th) {
+

2023-10-26 06:15 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/Task3/ConnectionException.java
> +        super("Connection Exception");
+

2023-10-26 09:33 UTC, infomouse requested changes

2023-10-26 09:33 UTC, infomouse commented on src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +        return null;
Не выполнено требование:
DefaultConnectionManager, который с некоторой вероятностью возвращает проблемное соединение

2023-10-26 09:33 UTC, infomouse commented on src/main/java/edu/hw2/task3/FaultyConnectionManager.java
> +public class FaultyConnectionManager implements ConnectionManager {
Не выполнено требование:
FaultyConnectionManager, который всегда возвращает проблемное соединение

2023-10-26 09:33 UTC, infomouse commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +    public boolean tryExecute(String command) {
Есть кейс, когда команда будет выполнена дважды. Попробуйте его найти через тесты.

2023-10-26 09:33 UTC, infomouse commented on src/test/java/edu/hw2/Task4Test.java
> +        var tst = Task4.callingInfo();
Не надо экономить буквы. Страдает читаемость кода.

2023-10-26 09:33 UTC, infomouse commented on src/test/java/edu/hw2/Task4Test.java
> +        assertThat(ans).isEqualTo(tst.toString());
Тут больше похоже на тест метода toString. Лучше только поля проверять.
```java
    @Test
    public void testCorrectness() {
        StackTraceElement[] stackTrace = Thread.currentThread().getStackTrace();

        Task4.CallingInfo result = Task4.callingInfo();

        assertNotNull(result);
        assertEquals(stackTrace[1].getClassName(), result.className());
        assertEquals(stackTrace[1].getMethodName(), result.methodName());
    }
```

2023-10-26 12:48 UTC, ViktorPetrovichBarinov commented on src/test/java/edu/hw2/Task4Test.java
> +        assertThat(ans).isEqualTo(tst.toString());
+

2023-10-26 12:49 UTC, ViktorPetrovichBarinov commented on src/test/java/edu/hw2/Task4Test.java
> +        var tst = Task4.callingInfo();
+

2023-10-26 13:24 UTC, ViktorPetrovichBarinov commented on src/test/java/edu/hw2/Task4Test.java
> +        assertThat(ans).isEqualTo(tst.toString());
+

2023-10-26 13:24 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/task3/DefaultConnectionManager.java
> +        return null;
+

2023-10-26 13:24 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/task3/FaultyConnectionManager.java
> +public class FaultyConnectionManager implements ConnectionManager {
+

2023-10-26 13:32 UTC, infomouse commented on src/main/java/edu/hw2/Task3/PopularCommandExecutor.java
> +public final class PopularCommandExecutor {
Пример теста с использованием мокито:
```java
class PopularCommandExecutorTest {
    private static final int MAX_ATTEMPS = 3;

    private ConnectionManager connectionManager = mock(ConnectionManager.class);

    private PopularCommandExecutor executor = new PopularCommandExecutor(connectionManager, MAX_ATTEMPS);

    @Test
    void testSuccessExecute() throws Exception {
        String command = "test";
        Connection connection = mock(Connection.class);
        when(connectionManager.getConnection()).thenReturn(connection);

        executor.tryExecute(command);

        verify(connection, times(1)).execute(command);
        verify(connection, times(1)).close();
    }
}
```

2023-10-26 16:36 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +    public boolean tryExecute(String command) {
+

2023-11-24 18:24 UTC, merged