Hw3
ViktorPetrovichBarinov/Tinkoff-23-24 pull request #4
Opened 2023-10-29 14:11 UTC by ViktorPetrovichBarinov

2023-10-31 20:39 UTC, infomouse requested changes

2023-10-31 20:39 UTC, infomouse commented on src/main/java/edu/hw3/Task2.java
> +                currentElementOfList = new StringBuilder();
Не самая удачная идея в плане производительности. Лучше использовать currentElementOfList.setLength(0) для очистки текущего, чем создавать каждый раз новый.

2023-10-31 20:39 UTC, infomouse commented on src/main/java/edu/hw3/Task3.java
> +            if (!dictionary.containsKey(elementOfInputArray)) {
Если есть возможность писать условие без отрицания, то лучше это делать. Такое условие легче воспринимать.

2023-10-31 20:39 UTC, infomouse commented on src/main/java/edu/hw3/Task4.java
> +        RomanData romanData = new RomanData(
Это должно быть константой, иначе на каждый вызов метода создаем одно и тоже.

2023-10-31 20:39 UTC, infomouse commented on src/main/java/edu/hw3/Task5.java
> +    public static ArrayList<Person> parseContacs(String[] inputArray, Enum order) {
Надо возвращать интерфейс List, а не конкретную реализацию. Это позволяет менять реализацию, не меняя контракт метода.

2023-10-31 20:39 UTC, infomouse commented on src/main/java/edu/hw3/Task5.java
> +    public static Comparator<Person> personComparator = new Comparator<Person>() {
Обычно такое делают в самом классе Person, реализуя интерфейс Comparable.

2023-11-03 21:03 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw3/Task2.java
> +                currentElementOfList = new StringBuilder();
+

2023-11-03 21:03 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw3/Task3.java
> +            if (!dictionary.containsKey(elementOfInputArray)) {
+

2023-11-03 21:05 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw3/Task4.java
> +        RomanData romanData = new RomanData(
+

2023-11-03 21:06 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw3/Task5.java
> +    public static ArrayList<Person> parseContacs(String[] inputArray, Enum order) {
+

2023-11-03 21:12 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw3/Task5.java
> +    public static Comparator<Person> personComparator = new Comparator<Person>() {
+

2023-11-24 18:25 UTC, merged