Hw5
ViktorPetrovichBarinov/Tinkoff-23-24 pull request #7
Opened 2023-11-12 14:37 UTC by ViktorPetrovichBarinov

2023-12-11 22:41 UTC, strelchm requested changes

2023-12-11 22:41 UTC, strelchm commented on src/main/java/edu/hw5/Task1.java
> +        long totalMinutes = averageTime / NUMBER_OF_SECONDS_IN_MINUTES;
Хорошо бы избежать лишнего кода - данный функционал уже есть в классе Duration.
Хорошо, что юзаешь метод Duration.between. Можно пойти дальше - в методе calculateTotalTime возвратить Duration - сумму от всех интеревалов времени, а наверху с помощью метода класса Duration найти среднее время, которое тоже будет типа Duration. Все операции по выводу в строку будут под капотом у Duration при таком подходе

2023-12-11 22:41 UTC, strelchm commented on src/main/java/edu/hw5/Task5.java
> +    private static final String LICENCE_PLATE_NUMBER_REGEX = "[А-Я]\\d{3}[А-Я]{2}\\d{3}";
- Буквы могут быть латинские в следующем диапазоне: `А, В, Е, К, М, Н, О, Р, С, Т, У и Х`
- Коды региона (последние цифры) могут быть трехзначные
[см. ](https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B7%D0%BD%D0%B0%D0%BA%D0%B8_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D1%8B%D1%85_%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2_%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8)

2023-12-11 22:41 UTC, strelchm commented on src/main/java/edu/hw5/Task7.java
> +    private static final String TASK7_REGEX1 = "[0.1]{2}0[0,1]*";
Следующая строка `.101` подходит под regexp, хотя у нас алфавит из 0 и 1

2023-12-16 11:49 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw5/Task1.java
> +        long totalMinutes = averageTime / NUMBER_OF_SECONDS_IN_MINUTES;
Исправил

2023-12-16 12:02 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw5/Task5.java
> +    private static final String LICENCE_PLATE_NUMBER_REGEX = "[А-Я]\\d{3}[А-Я]{2}\\d{3}";
Подозреваю, что имелось ввиду Подозреваю, что подозревалось: "и двузначные тоже".

2023-12-16 12:05 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw5/Task5.java
> +    private static final String LICENCE_PLATE_NUMBER_REGEX = "[А-Я]\\d{3}[А-Я]{2}\\d{3}";
Исправил

2023-12-16 12:10 UTC, ViktorPetrovichBarinov commented on src/main/java/edu/hw5/Task7.java
> +    private static final String TASK7_REGEX1 = "[0.1]{2}0[0,1]*";
Исправил

2023-12-17 21:08 UTC, strelchm approved these changes

2024-01-15 03:31 UTC, merged